name = "hpl-stripe-checkout"
main = "./.output/server/index.mjs"
account_id = "3247020fb40abaf1b3745a6584c13321"
workers_dev = true
compatibility_date = "2022-12-04"
route = "booking.highparklivery.com"

[site]
bucket = ".output/public"
